//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> SAL { get; set; }
        public Nullable<decimal> COMM_PCT { get; set; }
        public Nullable<decimal> PF { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> TEARN { get; set; }
        public Nullable<decimal> TDED { get; set; }
        public Nullable<decimal> NET { get; set; }
    }
}
